#!/usr/bin/with-contenv bash

# permissions
chown abc:abc \
    /data

# ipfs config
if [ ! -d "/data/.ipfs" ]; then
    HOME=/data ipfs init --profile lowpower
    chown -R abc:abc /data/.ipfs
fi

# link user data to frontend
if [ ! -L '/emulatorjs/frontend/user' ]; then
    ln -s /data /emulatorjs/frontend/user
fi

# nginx mime types
cp /defaults/mime.types /etc/nginx/mime.types
