#!/usr/bin/with-contenv bash

# permissions
chown abc:abc \
    /data

# ipfs config
if [ ! -d "/data/.ipfs" ]; then
    HOME=/data ipfs init --profile lowpower
    chown -R abc:abc /data/.ipfs
fi

# link user data to frontend
if [ ! -L '/emulatorjs/frontend/user' ]; then
    ln -s /data /emulatorjs/frontend/user
fi

# Default profile directory
if [ ! -d '/config/profile/default' ]; then
  mkdir -p /config/profile/default
  echo "input_menu_toggle_gamepad_combo = 3
system_directory = /home/web_user/retroarch/system/" > /config/profile/default/retroarch.cfg
  chown -R abc:abc /config/profile
fi
if [ ! -f '/config/profile/profile.json' ]; then
  echo '{}' > /config/profile/profile.json
  chown -R abc:abc /config/profile
fi

# nginx mime types
cp /defaults/mime.types /etc/nginx/mime.types

# nginx body cache
chown -R abc:root /var/lib/nginx

# allow users to mount in rom dirs
DIRS='3do atari2600 atari7800 colecovision doom gba lynx n64 nes odyssey2 psx segaCD segaMD segaSaturn snes vb ws arcade atari5200 gb gbc jaguar msx nds ngp pce sega32x segaGG segaMS segaSG vectrex'
for DIR in ${DIRS}; do
  if [ -d "/data/${DIR}" ]; then
    chown abc:abc "/data/${DIR}"
  fi
  if [ -d "/data/${DIR}/roms" ]; then
    chown abc:abc "/data/${DIR}/roms"
  fi
done
